---

- name : install mysql-server packages
  become : yes
  apt  :
    name  : "{{ item }}"
    state : "{{ mysqlserver_package_state }}"
    update_cache     : yes
    cache_valid_time : 3600
  environment:
    DEBIAN_FRONTEND: noninteractive
  with_items : "{{ mysqlserver_packages }}"
  notify :
    - restart mysql

